import legislators from "./openstates-w-legislators/w_state_legislators.js";

export const people = [
  {
    name: "John Lewis",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Lewis | GA-5",
    serviceStart: "January 1987",
    nextElection: "N/A",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Jim Jordan",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Jim Jordan | OH-4",
    serviceStart: "January 2007",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "Sheila Jackson Lee",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Sheila Jackson Lee | TX-18",
    serviceStart: "January 1995",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Maxine Waters",
    role: "Member of the U.S. House of Representatives",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS15guwf9K1B0OEYf_RkDMxjfQ3_cQcyzJEDw&s",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Maxine Waters | CA-43",
    serviceStart: "January 1991",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Liz Cheney",
    role: "Member of the U.S. House of Representatives",
    img: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Liz_Cheney_official_116th_Congress_portrait.jpg",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Liz Cheney | WY-At-Large",
    serviceStart: "January 2017",
    nextElection: "N/A",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "Lloyd Doggett",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Lloyd Doggett | TX-35",
    serviceStart: "January 1995",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Lauren Boebert",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Lauren Boebert | CO-3",
    serviceStart: "January 2021",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "Lisa Murkowski",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Lisa Murkowski | AK",
    serviceStart: "December 2002",
    nextElection: "November 2028",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Barrasso",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Barrasso | WY",
    serviceStart: "June 2007",
    nextElection: "November 2024",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Kennedy",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Kennedy | LA",
    serviceStart: "January 2017",
    nextElection: "November 2028",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "Ava Thompson",
    role: "Press Secretary",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "STAFFER",
    nameWithDistrict: "Ava Thompson | DC",
    serviceStart: "March 2022",
    nextElection: "",
    party: "",
    partyColor: "#5f6c85",
  },
  {
    name: "Mia Lewis",
    role: "Campaign Manager",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "STAFFER",
    nameWithDistrict: "Mia Lewis | DC",
    serviceStart: "June 2023",
    nextElection: "",
    party: "",
    partyColor: "#5f6c85",
  },
  {
    name: "Elijah Walker",
    role: "Public Affairs Director",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "STAFFER",
    nameWithDistrict: "Elijah Walker | DC",
    serviceStart: "February 2020",
    nextElection: "",
    party: "",
    partyColor: "#5f6c85",
  },
  {
    name: "Olivia Brown",
    role: "Federal Agency Director",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "AGENCY",
    nameWithDistrict: "Olivia Brown | EPA",
    serviceStart: "May 2018",
    nextElection: "",
    party: "",
    partyColor: "#5f6c85",
  },
  {
    name: "Robert Lee",
    role: "Federal Agency Staff",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "AGENCY",
    nameWithDistrict: "Robert Lee | EPA",
    serviceStart: "August 2019",
    nextElection: "",
    party: "",
    partyColor: "#5f6c85",
  },
  {
    name: "Sophia Martinez",
    role: "Committee Analyst",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "COMMITTEE",
    nameWithDistrict: "Sophia Martinez | House Committee",
    serviceStart: "January 2020",
    nextElection: "",
    party: "",
    partyColor: "#5f6c85",
  },
  {
    name: "Debbie Wasserman Schultz",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Debbie Wasserman Schultz | FL-25",
    serviceStart: "January 2005",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Lamar Alexander",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Lamar Alexander | TN",
    serviceStart: "January 2003",
    nextElection: "N/A",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "Jamie Raskin",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Jamie Raskin | MD-8",
    serviceStart: "January 2017",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "John Larson",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Larson | CT-1",
    serviceStart: "January 1999",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "William Timmons",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "William Timmons | SC-4",
    serviceStart: "January 2019",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "Lucy McBath",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Lucy McBath | GA-7",
    serviceStart: "January 2019",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Walter Jones",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Walter Jones | NC-3",
    serviceStart: "January 1995",
    nextElection: "N/A",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "Joaquin Castro",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Joaquin Castro | TX-20",
    serviceStart: "January 2013",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Jacky Rosen",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Jacky Rosen | NV",
    serviceStart: "January 2019",
    nextElection: "November 2024",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Jerry Nadler",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Jerry Nadler | NY-12",
    serviceStart: "November 1992",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Jim Langevin",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Jim Langevin | RI-2",
    serviceStart: "January 2001",
    nextElection: "N/A",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "John Yarmuth",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Yarmuth | KY-3",
    serviceStart: "January 2007",
    nextElection: "N/A",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "Lee Zeldin",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Lee Zeldin | NY-1",
    serviceStart: "January 2015",
    nextElection: "N/A",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "Jason Smith",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "Jason Smith | MO-8",
    serviceStart: "June 2013",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Cornyn",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Cornyn | TX",
    serviceStart: "December 2002",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Boozman",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Boozman | AR",
    serviceStart: "January 2011",
    nextElection: "November 2028",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Thune",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Thune | SD",
    serviceStart: "January 2005",
    nextElection: "November 2028",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Hoeven",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Hoeven | ND",
    serviceStart: "January 2011",
    nextElection: "November 2028",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Hickenlooper",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Hickenlooper | CO",
    serviceStart: "January 2021",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "John Fetterman",
    role: "Member of U.S. Senate",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Fetterman | PA",
    serviceStart: "January 2023",
    nextElection: "November 2028",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "John Garamendi",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Garamendi | CA-8",
    serviceStart: "November 2009",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "John Rutherford",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Rutherford | FL-5",
    serviceStart: "January 2017",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Sarbanes",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Sarbanes | MD-3",
    serviceStart: "January 2007",
    nextElection: "November 2026",
    party: "D",
    partyColor: "#0073ba",
  },
  {
    name: "John Katko",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Katko | NY-24",
    serviceStart: "January 2015",
    nextElection: "N/A",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Curtis",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Curtis | UT-3",
    serviceStart: "November 2017",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Carter",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Carter | TX-31",
    serviceStart: "January 2003",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Joyce",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Joyce | PA-13",
    serviceStart: "January 2019",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Moolenaar",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Moolenaar | MI-2",
    serviceStart: "January 2015",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Rose",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Rose | TN-6",
    serviceStart: "January 2019",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Rutherford",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Rutherford | FL-5",
    serviceStart: "January 2017",
    nextElection: "November 2026",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Shimkus",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Shimkus | IL-15",
    serviceStart: "January 1997",
    nextElection: "N/A",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "John Faso",
    role: "Member of the U.S. House of Representatives",
    img: "",
    location: "Federal",
    type: "People",
    memberType: "MEMBER",
    nameWithDistrict: "John Faso | NY-19",
    serviceStart: "January 2017",
    nextElection: "N/A",
    party: "R",
    partyColor: "#c8102e",
  },
  {
    name: "House Committee on Appropriations",
    role: "Chair",
    img: "img/congress-committee-icon.svg", // SVG icon for committees
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Senate Committee on Finance",
    role: "Ranking Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "House Committee on Energy and Commerce",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Senate Committee on Judiciary",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "House Committee on Foreign Affairs",
    role: "Chair",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Senate Committee on Armed Services",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "House Committee on Ways and Means",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Senate Committee on Health, Education, Labor, and Pensions",
    role: "Chair",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "House Committee on Homeland Security",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Senate Committee on Environment and Public Works",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "House Committee on the Judiciary",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Senate Committee on the Judiciary",
    role: "Chair",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "House Subcommittee on Water Resources and Environment",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Senate Subcommittee on Water and Power",
    role: "Ranking Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "House Committee on Natural Resources",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "House Subcommittee on Crime, Terrorism, and Homeland Security",
    role: "Chair",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Senate Subcommittee on Privacy, Technology, and the Law",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "House Subcommittee on Courts, Intellectual Property, and the Internet",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Senate Subcommittee on Human Rights and the Law",
    role: "Ranking Member",
    img: "img/congress-committee-icon.svg",
    location: "Federal",
    type: "Committees",
  },
  {
    name: "Natural Resources and Water Committee, California State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "State",
    type: "Committees",
  },
  {
    name: "Water, Parks, and Wildlife Committee, California State Assembly",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Natural Resources Committee, Arizona State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Water, Agriculture, & Rural Affairs Committee, Texas State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Joint Water Supply During Drought Committee, Washington State Legislature",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Water & Land Committee, Hawaii State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Water & Land Committee, Hawaii House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Alaska House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Alaska State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Kansas House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Kansas State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Kentucky General Assembly",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Kentucky State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Kentucky House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Maine State Legislature",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Maryland House of Delegates",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Michigan House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Michigan State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Missouri House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Montana House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Montana State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Pennsylvania House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, South Carolina State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, South Dakota House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, South Dakota State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Tennessee State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Utah House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Vermont House of Representatives",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "state",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Virginia State Senate",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "State",
    type: "Committees",
  },
  {
    name: "Judiciary Committee, Wisconsin State Assembly",
    role: "Member",
    img: "img/congress-committee-icon.svg",
    location: "State",
    type: "Committees",
  },
  // Federal - Agencies
  {
    name: "U.S. Bureau of Reclamation",
    role: "Federal Agency",
    img: "img/agency-icon.svg",
    location: "Federal",
    type: "Agencies",
  },
  {
    name: "U.S. Geological Survey Water Resources Division",
    role: "Federal Agency",
    img: "img/agency-icon.svg",
    location: "Federal",
    type: "Agencies",
  },
  {
    name: "Environmental Protection Agency Office of Water",
    role: "Federal Agency",
    img: "img/agency-icon.svg",
    location: "Federal",
    type: "Agencies",
  },
  {
    name: "U.S. Department of Justice",
    role: "Federal Agency (Judicial)",
    img: "img/agency-icon.svg",
    location: "Federal",
    type: "Agencies",
  },
  {
    name: "Administrative Office of the U.S. Courts",
    role: "Federal Agency (Judicial)",
    img: "img/agency-icon.svg",
    location: "Federal",
    type: "Agencies",
  },
  {
    name: "Federal Judicial Center",
    role: "Federal Agency (Judicial)",
    img: "img/agency-icon.svg",
    location: "Federal",
    type: "Agencies",
  },
  {
    name: "Office of the Law Revision Counsel",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "Federal",
    type: "Agencies",
  },
  {
    name: "Library of Congress Law Library",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "Federal",
    type: "Agencies",
  },
  {
    name: "California Department of Water Resources",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Texas Commission on Environmental Quality",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "New York State Department of Environmental Conservation",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Florida Department of Law Enforcement",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Illinois State Police",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Pennsylvania Office of Attorney General",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Ohio Department of Natural Resources",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Michigan Department of Civil Rights",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Georgia Bureau of Investigation",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Washington State Department of Ecology",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Colorado Department of Public Safety",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "North Carolina Department of Justice",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Arizona Department of Water Resources",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Massachusetts Executive Office of Public Safety and Security",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
  {
    name: "Virginia Department of Environmental Quality",
    role: "Federal Agency (Law)",
    img: "img/agency-icon.svg",
    location: "State",
    type: "Agencies",
  },
].map((person) => {
  if (person.role === "Representative") {
    return { ...person, role: "Member of the U.S. House of Representatives" };
  }
  if (person.role === "Senator") {
    return { ...person, role: "Member of U.S. Senate" };
  }
  return person;
});

const allPeople = [...people, ...legislators];

export const bios = [
  { id: 1, bio: "John Doe is a Senator from California." },
  { id: 2, bio: "Jane Smith is a Representative from Texas." },
  { id: 3, bio: "Emily Johnson is the Governor of New York." },
];
