/**
 * generate-data.js
 * Run once: node generate-data.js
 * Outputs:
 *   - data/{key}.json  (tournament history per team)
 *   - teams-index.json (all teams metadata, loaded by landing + team-view)
 */

const fs = require("fs");
const path = require("path");

const DATA_DIR = path.join(__dirname, "data");
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR);

// ---------------------------------------------------------------------------
// All World Cup participating nations
// key        – URL param / filename
// name       – display name
// abbr       – FIFA three-letter code
// conf       – confederation
// titles     – number of WC titles
// gp/w/d/l/gs/ga – all-time totals (through 2022)
// points     – FIFA all-time WC ranking points (approx)
// tournaments – array of { year, stage }
//   stage codes: W=winner, RU=runner-up, SF=semi, 3P=3rd, 4P=4th,
//                QF=quarter, 2GS=2nd group stage, R16=round of 16,
//                GS=group stage, DNQ=did not qualify,
//                DNE=did not enter, WD=withdrew, BAN=banned
// ---------------------------------------------------------------------------

const TEAMS = [
	// ── CONMEBOL ──────────────────────────────────────────────────────────────
	{
		key: "brazil",
		name: "Brazil",
		abbr: "BRA",
		conf: "CONMEBOL",
		titles: 5,
		points: 247,
		gp: 114,
		w: 76,
		d: 19,
		l: 19,
		gs: 237,
		ga: 108,
		badge:
			"https://r2.thesportsdb.com/images/media/team/badge/jl6dip1726167280.png",
		tournaments: [
			{ year: 1930, stage: "SF" },
			{ year: 1934, stage: "R16" },
			{ year: 1938, stage: "SF" },
			{ year: 1950, stage: "RU" },
			{ year: 1954, stage: "QF" },
			{ year: 1958, stage: "W" },
			{ year: 1962, stage: "W" },
			{ year: 1966, stage: "GS" },
			{ year: 1970, stage: "W" },
			{ year: 1974, stage: "4P" },
			{ year: 1978, stage: "3P" },
			{ year: 1982, stage: "2GS" },
			{ year: 1986, stage: "QF" },
			{ year: 1990, stage: "R16" },
			{ year: 1994, stage: "W" },
			{ year: 1998, stage: "RU" },
			{ year: 2002, stage: "W" },
			{ year: 2006, stage: "QF" },
			{ year: 2010, stage: "QF" },
			{ year: 2014, stage: "SF" },
			{ year: 2018, stage: "QF" },
			{ year: 2022, stage: "QF" },
		],
	},
	{
		key: "argentina",
		name: "Argentina",
		abbr: "ARG",
		conf: "CONMEBOL",
		titles: 3,
		points: 144,
		gp: 88,
		w: 47,
		d: 17,
		l: 24,
		gs: 143,
		ga: 98,
		badge:
			"https://r2.thesportsdb.com/images/media/team/badge/3zplhu1726167477.png",
		tournaments: [
			{ year: 1930, stage: "RU" },
			{ year: 1934, stage: "R16" },
			{ year: 1938, stage: "WD" },
			{ year: 1950, stage: "DNE" },
			{ year: 1954, stage: "WD" },
			{ year: 1958, stage: "GS" },
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "QF" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "2GS" },
			{ year: 1978, stage: "W" },
			{ year: 1982, stage: "2GS" },
			{ year: 1986, stage: "W" },
			{ year: 1990, stage: "RU" },
			{ year: 1994, stage: "GS" },
			{ year: 1998, stage: "QF" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "QF" },
			{ year: 2010, stage: "QF" },
			{ year: 2014, stage: "RU" },
			{ year: 2018, stage: "R16" },
			{ year: 2022, stage: "W" },
		],
	},
	{
		key: "uruguay",
		name: "Uruguay",
		abbr: "URU",
		conf: "CONMEBOL",
		titles: 2,
		points: 83,
		gp: 56,
		w: 28,
		d: 12,
		l: 16,
		gs: 94,
		ga: 65,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Uruguay_national_football_team_crest.svg/200px-Uruguay_national_football_team_crest.svg.png",
		tournaments: [
			{ year: 1930, stage: "W" },
			{ year: 1934, stage: "DNE" },
			{ year: 1938, stage: "DNE" },
			{ year: 1950, stage: "W" },
			{ year: 1954, stage: "SF" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "QF" },
			{ year: 1970, stage: "SF" },
			{ year: 1974, stage: "2GS" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "R16" },
			{ year: 1990, stage: "R16" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "DNQ" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "DNQ" },
			{ year: 2010, stage: "SF" },
			{ year: 2014, stage: "R16" },
			{ year: 2018, stage: "QF" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "chile",
		name: "Chile",
		abbr: "CHI",
		conf: "CONMEBOL",
		titles: 0,
		points: 40,
		gp: 37,
		w: 16,
		d: 7,
		l: 14,
		gs: 65,
		ga: 63,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Chile_national_football_team_badge.svg/200px-Chile_national_football_team_badge.svg.png",
		tournaments: [
			{ year: 1930, stage: "SF" },
			{ year: 1934, stage: "DNQ" },
			{ year: 1938, stage: "DNQ" },
			{ year: 1950, stage: "GS" },
			{ year: 1954, stage: "GS" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "3P" },
			{ year: 1966, stage: "GS" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "2GS" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "GS" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "R16" },
			{ year: 2002, stage: "DNQ" },
			{ year: 2006, stage: "DNQ" },
			{ year: 2010, stage: "R16" },
			{ year: 2014, stage: "R16" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "DNQ" },
		],
	},
	{
		key: "colombia",
		name: "Colombia",
		abbr: "COL",
		conf: "CONMEBOL",
		titles: 0,
		points: 28,
		gp: 28,
		w: 13,
		d: 5,
		l: 10,
		gs: 45,
		ga: 36,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Colombia_national_football_team_badge.svg/200px-Colombia_national_football_team_badge.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "DNQ" },
			{ year: 1938, stage: "DNQ" },
			{ year: 1950, stage: "DNQ" },
			{ year: 1954, stage: "DNQ" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "DNQ" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "R16" },
			{ year: 1994, stage: "GS" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "DNQ" },
			{ year: 2006, stage: "DNQ" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "QF" },
			{ year: 2018, stage: "R16" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "peru",
		name: "Peru",
		abbr: "PER",
		conf: "CONMEBOL",
		titles: 0,
		points: 16,
		gp: 15,
		w: 4,
		d: 3,
		l: 8,
		gs: 19,
		ga: 31,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Peru_national_football_team_badge.png/200px-Peru_national_football_team_badge.png",
		tournaments: [
			{ year: 1930, stage: "GS" },
			{ year: 1934, stage: "R16" },
			{ year: 1938, stage: "WD" },
			{ year: 1950, stage: "DNQ" },
			{ year: 1954, stage: "DNQ" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "QF" },
			{ year: 1974, stage: "2GS" },
			{ year: 1978, stage: "2GS" },
			{ year: 1982, stage: "GS" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "DNQ" },
			{ year: 2002, stage: "DNQ" },
			{ year: 2006, stage: "DNQ" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "DNQ" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "DNQ" },
		],
	},
	{
		key: "paraguay",
		name: "Paraguay",
		abbr: "PAR",
		conf: "CONMEBOL",
		titles: 0,
		points: 20,
		gp: 22,
		w: 7,
		d: 7,
		l: 8,
		gs: 30,
		ga: 38,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Paraguay_national_football_team_logo.svg/200px-Paraguay_national_football_team_logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "GS" },
			{ year: 1934, stage: "DNQ" },
			{ year: 1938, stage: "WD" },
			{ year: 1950, stage: "GS" },
			{ year: 1954, stage: "DNQ" },
			{ year: 1958, stage: "GS" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "DNQ" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "R16" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "R16" },
			{ year: 2002, stage: "R16" },
			{ year: 2006, stage: "R16" },
			{ year: 2010, stage: "QF" },
			{ year: 2014, stage: "DNQ" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "DNQ" },
		],
	},
	{
		key: "ecuador",
		name: "Ecuador",
		abbr: "ECU",
		conf: "CONMEBOL",
		titles: 0,
		points: 10,
		gp: 13,
		w: 4,
		d: 2,
		l: 7,
		gs: 14,
		ga: 21,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Ecuador_national_football_team_badge.svg/200px-Ecuador_national_football_team_badge.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "DNQ" },
			{ year: 1938, stage: "DNQ" },
			{ year: 1950, stage: "DNQ" },
			{ year: 1954, stage: "DNQ" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "DNQ" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "DNQ" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "R16" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "bolivia",
		name: "Bolivia",
		abbr: "BOL",
		conf: "CONMEBOL",
		titles: 0,
		points: 3,
		gp: 6,
		w: 0,
		d: 2,
		l: 4,
		gs: 5,
		ga: 20,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Bolivia_national_football_team_badge.svg/200px-Bolivia_national_football_team_badge.svg.png",
		tournaments: [
			{ year: 1930, stage: "GS" },
			{ year: 1934, stage: "WD" },
			{ year: 1938, stage: "WD" },
			{ year: 1950, stage: "GS" },
			{ year: 1954, stage: "DNQ" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "DNQ" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "GS" },
			{ year: 1998, stage: "DNQ" },
			{ year: 2002, stage: "DNQ" },
			{ year: 2006, stage: "DNQ" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "DNQ" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "DNQ" },
		],
	},

	// ── UEFA ──────────────────────────────────────────────────────────────────
	{
		key: "germany",
		name: "Germany",
		abbr: "GER",
		conf: "UEFA",
		titles: 4,
		points: 221,
		gp: 113,
		w: 68,
		d: 21,
		l: 24,
		gs: 232,
		ga: 130,
		badge:
			"https://r2.thesportsdb.com/images/media/team/badge/1xysi51726167152.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "3P" },
			{ year: 1938, stage: "R16" },
			{ year: 1950, stage: "BAN" },
			{ year: 1954, stage: "W" },
			{ year: 1958, stage: "SF" },
			{ year: 1962, stage: "QF" },
			{ year: 1966, stage: "RU" },
			{ year: 1970, stage: "3P" },
			{ year: 1974, stage: "W" },
			{ year: 1978, stage: "2GS" },
			{ year: 1982, stage: "RU" },
			{ year: 1986, stage: "RU" },
			{ year: 1990, stage: "W" },
			{ year: 1994, stage: "QF" },
			{ year: 1998, stage: "QF" },
			{ year: 2002, stage: "RU" },
			{ year: 2006, stage: "3P" },
			{ year: 2010, stage: "3P" },
			{ year: 2014, stage: "W" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "italy",
		name: "Italy",
		abbr: "ITA",
		conf: "UEFA",
		titles: 4,
		points: 156,
		gp: 83,
		w: 45,
		d: 21,
		l: 17,
		gs: 128,
		ga: 77,
		badge:
			"https://r2.thesportsdb.com/images/media/team/badge/fxijcp1726167035.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "W" },
			{ year: 1938, stage: "W" },
			{ year: 1950, stage: "GS" },
			{ year: 1954, stage: "GS" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "GS" },
			{ year: 1970, stage: "RU" },
			{ year: 1974, stage: "GS" },
			{ year: 1978, stage: "4P" },
			{ year: 1982, stage: "W" },
			{ year: 1986, stage: "R16" },
			{ year: 1990, stage: "3P" },
			{ year: 1994, stage: "RU" },
			{ year: 1998, stage: "QF" },
			{ year: 2002, stage: "R16" },
			{ year: 2006, stage: "W" },
			{ year: 2010, stage: "GS" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "DNQ" },
		],
	},
	{
		key: "france",
		name: "France",
		abbr: "FRA",
		conf: "UEFA",
		titles: 2,
		points: 115,
		gp: 70,
		w: 35,
		d: 13,
		l: 22,
		gs: 130,
		ga: 82,
		badge:
			"https://r2.thesportsdb.com/images/media/team/badge/p3n0z51726166851.png",
		tournaments: [
			{ year: 1930, stage: "GS" },
			{ year: 1934, stage: "R16" },
			{ year: 1938, stage: "QF" },
			{ year: 1950, stage: "DNQ" },
			{ year: 1954, stage: "GS" },
			{ year: 1958, stage: "3P" },
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "GS" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "DNQ" },
			{ year: 1978, stage: "GS" },
			{ year: 1982, stage: "SF" },
			{ year: 1986, stage: "3P" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "W" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "RU" },
			{ year: 2010, stage: "GS" },
			{ year: 2014, stage: "QF" },
			{ year: 2018, stage: "W" },
			{ year: 2022, stage: "RU" },
		],
	},
	{
		key: "spain",
		name: "Spain",
		abbr: "ESP",
		conf: "UEFA",
		titles: 1,
		points: 107,
		gp: 66,
		w: 35,
		d: 14,
		l: 17,
		gs: 111,
		ga: 72,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Spain_national_football_team_badge.svg/200px-Spain_national_football_team_badge.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "QF" },
			{ year: 1938, stage: "WD" },
			{ year: 1950, stage: "4P" },
			{ year: 1954, stage: "GS" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "GS" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "GS" },
			{ year: 1978, stage: "GS" },
			{ year: 1982, stage: "2GS" },
			{ year: 1986, stage: "QF" },
			{ year: 1990, stage: "R16" },
			{ year: 1994, stage: "QF" },
			{ year: 1998, stage: "R16" },
			{ year: 2002, stage: "QF" },
			{ year: 2006, stage: "R16" },
			{ year: 2010, stage: "W" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "R16" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "england",
		name: "England",
		abbr: "ENG",
		conf: "UEFA",
		titles: 1,
		points: 91,
		gp: 69,
		w: 32,
		d: 19,
		l: 18,
		gs: 96,
		ga: 68,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/200px-Flag_of_England.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "DNE" },
			{ year: 1938, stage: "DNE" },
			{ year: 1950, stage: "GS" },
			{ year: 1954, stage: "QF" },
			{ year: 1958, stage: "GS" },
			{ year: 1962, stage: "QF" },
			{ year: 1966, stage: "W" },
			{ year: 1970, stage: "QF" },
			{ year: 1974, stage: "DNQ" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "2GS" },
			{ year: 1986, stage: "QF" },
			{ year: 1990, stage: "SF" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "R16" },
			{ year: 2002, stage: "QF" },
			{ year: 2006, stage: "QF" },
			{ year: 2010, stage: "R16" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "SF" },
			{ year: 2022, stage: "QF" },
		],
	},
	{
		key: "netherlands",
		name: "Netherlands",
		abbr: "NED",
		conf: "UEFA",
		titles: 0,
		points: 110,
		gp: 57,
		w: 30,
		d: 11,
		l: 16,
		gs: 99,
		ga: 68,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Royal_Dutch_Football_Association_logo.svg/200px-Royal_Dutch_Football_Association_logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "R16" },
			{ year: 1938, stage: "QF" },
			{ year: 1950, stage: "DNE" },
			{ year: 1954, stage: "DNQ" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "RU" },
			{ year: 1978, stage: "RU" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "R16" },
			{ year: 1994, stage: "QF" },
			{ year: 1998, stage: "SF" },
			{ year: 2002, stage: "DNQ" },
			{ year: 2006, stage: "R16" },
			{ year: 2010, stage: "RU" },
			{ year: 2014, stage: "3P" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "QF" },
		],
	},
	{
		key: "portugal",
		name: "Portugal",
		abbr: "POR",
		conf: "UEFA",
		titles: 0,
		points: 60,
		gp: 39,
		w: 20,
		d: 8,
		l: 11,
		gs: 63,
		ga: 42,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/Football_Portugal.gif/200px-Football_Portugal.gif",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "DNQ" },
			{ year: 1938, stage: "DNQ" },
			{ year: 1950, stage: "DNQ" },
			{ year: 1954, stage: "DNQ" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "3P" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "GS" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "QF" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "SF" },
			{ year: 2010, stage: "R16" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "QF" },
			{ year: 2022, stage: "SF" },
		],
	},
	{
		key: "belgium",
		name: "Belgium",
		abbr: "BEL",
		conf: "UEFA",
		titles: 0,
		points: 63,
		gp: 47,
		w: 21,
		d: 11,
		l: 15,
		gs: 77,
		ga: 61,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Belgium_national_football_team_logo.svg/200px-Belgium_national_football_team_logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "GS" },
			{ year: 1934, stage: "R16" },
			{ year: 1938, stage: "R16" },
			{ year: 1950, stage: "GS" },
			{ year: 1954, stage: "GS" },
			{ year: 1958, stage: "GS" },
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "GS" },
			{ year: 1974, stage: "DNQ" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "2GS" },
			{ year: 1986, stage: "4P" },
			{ year: 1990, stage: "R16" },
			{ year: 1994, stage: "R16" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "R16" },
			{ year: 2006, stage: "GS" },
			{ year: 2010, stage: "GS" },
			{ year: 2014, stage: "R16" },
			{ year: 2018, stage: "SF" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "sweden",
		name: "Sweden",
		abbr: "SWE",
		conf: "UEFA",
		titles: 0,
		points: 58,
		gp: 50,
		w: 18,
		d: 12,
		l: 20,
		gs: 82,
		ga: 85,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/Sweden_national_football_team_badge.svg/200px-Sweden_national_football_team_badge.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "QF" },
			{ year: 1938, stage: "SF" },
			{ year: 1950, stage: "3P" },
			{ year: 1954, stage: "GS" },
			{ year: 1958, stage: "RU" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "GS" },
			{ year: 1974, stage: "2GS" },
			{ year: 1978, stage: "GS" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "R16" },
			{ year: 1994, stage: "3P" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "R16" },
			{ year: 2006, stage: "R16" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "DNQ" },
			{ year: 2018, stage: "R16" },
			{ year: 2022, stage: "DNQ" },
		],
	},
	{
		key: "poland",
		name: "Poland",
		abbr: "POL",
		conf: "UEFA",
		titles: 0,
		points: 38,
		gp: 34,
		w: 15,
		d: 5,
		l: 14,
		gs: 49,
		ga: 45,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Polish_Football_Association_logo.svg/200px-Polish_Football_Association_logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "R16" },
			{ year: 1938, stage: "QF" },
			{ year: 1950, stage: "DNE" },
			{ year: 1954, stage: "DNQ" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "3P" },
			{ year: 1978, stage: "3P" },
			{ year: 1982, stage: "3P" },
			{ year: 1986, stage: "R16" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "DNQ" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "GS" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "DNQ" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "croatia",
		name: "Croatia",
		abbr: "CRO",
		conf: "UEFA",
		titles: 0,
		points: 54,
		gp: 27,
		w: 14,
		d: 5,
		l: 8,
		gs: 46,
		ga: 34,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/Croatia_national_football_team_logo.svg/200px-Croatia_national_football_team_logo.svg.png",
		tournaments: [
			{ year: 1998, stage: "3P" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "GS" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "RU" },
			{ year: 2022, stage: "3P" },
		],
	},
	{
		key: "russia",
		name: "Russia",
		abbr: "RUS",
		conf: "UEFA",
		titles: 0,
		points: 22,
		gp: 27,
		w: 9,
		d: 7,
		l: 11,
		gs: 37,
		ga: 38,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/0/0e/Russian_Football_Union_logo.svg/200px-Russian_Football_Union_logo.svg.png",
		tournaments: [
			{ year: 1994, stage: "GS" },
			{ year: 1998, stage: "DNQ" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "DNQ" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "QF" },
			{ year: 2022, stage: "BAN" },
		],
	},
	{
		key: "denmark",
		name: "Denmark",
		abbr: "DEN",
		conf: "UEFA",
		titles: 0,
		points: 24,
		gp: 22,
		w: 8,
		d: 5,
		l: 9,
		gs: 33,
		ga: 37,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/DBU_Logo.svg/200px-DBU_Logo.svg.png",
		tournaments: [
			{ year: 1986, stage: "R16" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "QF" },
			{ year: 2002, stage: "R16" },
			{ year: 2006, stage: "DNQ" },
			{ year: 2010, stage: "GS" },
			{ year: 2014, stage: "DNQ" },
			{ year: 2018, stage: "R16" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "switzerland",
		name: "Switzerland",
		abbr: "SUI",
		conf: "UEFA",
		titles: 0,
		points: 28,
		gp: 36,
		w: 11,
		d: 9,
		l: 16,
		gs: 50,
		ga: 62,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Swiss_Football_Association_logo.svg/200px-Swiss_Football_Association_logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "QF" },
			{ year: 1938, stage: "QF" },
			{ year: 1950, stage: "GS" },
			{ year: 1954, stage: "QF" },
			{ year: 1958, stage: "GS" },
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "GS" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "GS" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "R16" },
			{ year: 1994, stage: "R16" },
			{ year: 1998, stage: "DNQ" },
			{ year: 2002, stage: "DNQ" },
			{ year: 2006, stage: "R16" },
			{ year: 2010, stage: "R16" },
			{ year: 2014, stage: "R16" },
			{ year: 2018, stage: "R16" },
			{ year: 2022, stage: "QF" },
		],
	},
	{
		key: "austria",
		name: "Austria",
		abbr: "AUT",
		conf: "UEFA",
		titles: 0,
		points: 18,
		gp: 29,
		w: 12,
		d: 4,
		l: 13,
		gs: 43,
		ga: 47,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/OFB-Logo.svg/200px-OFB-Logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "SF" },
			{ year: 1938, stage: "WD" },
			{ year: 1950, stage: "DNE" },
			{ year: 1954, stage: "3P" },
			{ year: 1958, stage: "GS" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "DNQ" },
			{ year: 1974, stage: "DNQ" },
			{ year: 1978, stage: "2GS" },
			{ year: 1982, stage: "GS" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "GS" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "DNQ" },
			{ year: 2006, stage: "GS" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "DNQ" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "DNQ" },
		],
	},
	{
		key: "hungary",
		name: "Hungary",
		abbr: "HUN",
		conf: "UEFA",
		titles: 0,
		points: 24,
		gp: 32,
		w: 15,
		d: 3,
		l: 14,
		gs: 87,
		ga: 57,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/MLSZ_logo.svg/200px-MLSZ_logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "DNE" },
			{ year: 1934, stage: "QF" },
			{ year: 1938, stage: "RU" },
			{ year: 1950, stage: "DNE" },
			{ year: 1954, stage: "RU" },
			{ year: 1958, stage: "GS" },
			{ year: 1962, stage: "QF" },
			{ year: 1966, stage: "GS" },
			{ year: 1970, stage: "GS" },
			{ year: 1974, stage: "GS" },
			{ year: 1978, stage: "GS" },
			{ year: 1982, stage: "GS" },
			{ year: 1986, stage: "GS" },
			{ year: 1990, stage: "DNQ" },
			{ year: 1994, stage: "DNQ" },
			{ year: 1998, stage: "DNQ" },
			{ year: 2002, stage: "DNQ" },
			{ year: 2006, stage: "DNQ" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "DNQ" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "DNQ" },
		],
	},
	{
		key: "czech-republic",
		name: "Czech Republic",
		abbr: "CZE",
		conf: "UEFA",
		titles: 0,
		points: 18,
		gp: 19,
		w: 8,
		d: 4,
		l: 7,
		gs: 30,
		ga: 26,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Football_Association_of_Czech_Republic_logo.svg/200px-Football_Association_of_Czech_Republic_logo.svg.png",
		tournaments: [
			// as Czechoslovakia:
			{ year: 1934, stage: "RU" },
			{ year: 1938, stage: "QF" },
			{ year: 1954, stage: "GS" },
			{ year: 1958, stage: "GS" },
			{ year: 1962, stage: "RU" },
			{ year: 1970, stage: "GS" },
			{ year: 1982, stage: "GS" },
			// as Czech Republic:
			{ year: 2006, stage: "GS" },
		],
	},
	{
		key: "romania",
		name: "Romania",
		abbr: "ROU",
		conf: "UEFA",
		titles: 0,
		points: 18,
		gp: 21,
		w: 8,
		d: 5,
		l: 8,
		gs: 30,
		ga: 32,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Federatia_Romana_de_Fotbal_logo.svg/200px-Federatia_Romana_de_Fotbal_logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "GS" },
			{ year: 1934, stage: "R16" },
			{ year: 1938, stage: "R16" },
			{ year: 1950, stage: "DNQ" },
			{ year: 1954, stage: "DNQ" },
			{ year: 1958, stage: "DNQ" },
			{ year: 1962, stage: "DNQ" },
			{ year: 1966, stage: "DNQ" },
			{ year: 1970, stage: "GS" },
			{ year: 1974, stage: "GS" },
			{ year: 1978, stage: "DNQ" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "DNQ" },
			{ year: 1990, stage: "R16" },
			{ year: 1994, stage: "QF" },
			{ year: 1998, stage: "R16" },
			{ year: 2002, stage: "DNQ" },
			{ year: 2006, stage: "DNQ" },
			{ year: 2010, stage: "DNQ" },
			{ year: 2014, stage: "DNQ" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "DNQ" },
		],
	},
	{
		key: "turkey",
		name: "Turkey",
		abbr: "TUR",
		conf: "UEFA",
		titles: 0,
		points: 17,
		gp: 10,
		w: 5,
		d: 1,
		l: 4,
		gs: 20,
		ga: 17,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/TFF_logo.svg/200px-TFF_logo.svg.png",
		tournaments: [
			{ year: 1954, stage: "GS" },
			{ year: 2002, stage: "3P" },
		],
	},
	{
		key: "greece",
		name: "Greece",
		abbr: "GRE",
		conf: "UEFA",
		titles: 0,
		points: 6,
		gp: 9,
		w: 0,
		d: 2,
		l: 7,
		gs: 8,
		ga: 20,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/EPO_logo.svg/200px-EPO_logo.svg.png",
		tournaments: [
			{ year: 1994, stage: "GS" },
			{ year: 2010, stage: "GS" },
		],
	},
	{
		key: "norway",
		name: "Norway",
		abbr: "NOR",
		conf: "UEFA",
		titles: 0,
		points: 8,
		gp: 8,
		w: 2,
		d: 2,
		l: 4,
		gs: 7,
		ga: 8,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Football_Federation_Norway_logo.svg/200px-Football_Federation_Norway_logo.svg.png",
		tournaments: [
			{ year: 1938, stage: "R16" },
			{ year: 1994, stage: "R16" },
			{ year: 1998, stage: "R16" },
		],
	},
	{
		key: "scotland",
		name: "Scotland",
		abbr: "SCO",
		conf: "UEFA",
		titles: 0,
		points: 9,
		gp: 23,
		w: 4,
		d: 7,
		l: 12,
		gs: 25,
		ga: 41,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/SFA_logo.svg/200px-SFA_logo.svg.png",
		tournaments: [
			{ year: 1954, stage: "GS" },
			{ year: 1958, stage: "GS" },
			{ year: 1974, stage: "GS" },
			{ year: 1978, stage: "GS" },
			{ year: 1982, stage: "GS" },
			{ year: 1986, stage: "GS" },
			{ year: 1990, stage: "GS" },
			{ year: 1998, stage: "GS" },
		],
	},
	{
		key: "ireland",
		name: "Republic of Ireland",
		abbr: "IRL",
		conf: "UEFA",
		titles: 0,
		points: 11,
		gp: 13,
		w: 2,
		d: 6,
		l: 5,
		gs: 10,
		ga: 17,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/a/a5/Football_Association_of_Ireland_Badge.svg/200px-Football_Association_of_Ireland_Badge.svg.png",
		tournaments: [
			{ year: 1990, stage: "QF" },
			{ year: 1994, stage: "R16" },
		],
	},
	{
		key: "wales",
		name: "Wales",
		abbr: "WAL",
		conf: "UEFA",
		titles: 0,
		points: 5,
		gp: 5,
		w: 1,
		d: 1,
		l: 3,
		gs: 4,
		ga: 9,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/FAW_logo.svg/200px-FAW_logo.svg.png",
		tournaments: [
			{ year: 1958, stage: "QF" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "serbia",
		name: "Serbia",
		abbr: "SRB",
		conf: "UEFA",
		titles: 0,
		points: 14,
		gp: 20,
		w: 6,
		d: 4,
		l: 10,
		gs: 27,
		ga: 37,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/FSS_Logo.svg/200px-FSS_Logo.svg.png",
		tournaments: [
			// Yugoslavia appearances:
			{ year: 1930, stage: "SF" },
			{ year: 1950, stage: "GS" },
			{ year: 1954, stage: "QF" },
			{ year: 1958, stage: "QF" },
			{ year: 1962, stage: "RU" },
			{ year: 1974, stage: "2GS" },
			{ year: 1982, stage: "GS" },
			// Serbia & Montenegro:
			{ year: 2006, stage: "GS" },
			// Serbia:
			{ year: 2010, stage: "GS" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "ukraine",
		name: "Ukraine",
		abbr: "UKR",
		conf: "UEFA",
		titles: 0,
		points: 10,
		gp: 6,
		w: 3,
		d: 0,
		l: 3,
		gs: 10,
		ga: 9,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/FFU_logo.svg/200px-FFU_logo.svg.png",
		tournaments: [{ year: 2006, stage: "QF" }],
	},
	{
		key: "slovakia",
		name: "Slovakia",
		abbr: "SVK",
		conf: "UEFA",
		titles: 0,
		points: 7,
		gp: 7,
		w: 2,
		d: 1,
		l: 4,
		gs: 8,
		ga: 12,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Slovak_Football_Association_logo.svg/200px-Slovak_Football_Association_logo.svg.png",
		tournaments: [{ year: 2010, stage: "R16" }],
	},
	{
		key: "slovenia",
		name: "Slovenia",
		abbr: "SVN",
		conf: "UEFA",
		titles: 0,
		points: 4,
		gp: 7,
		w: 1,
		d: 2,
		l: 4,
		gs: 5,
		ga: 10,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/NZS_logo.svg/200px-NZS_logo.svg.png",
		tournaments: [
			{ year: 2002, stage: "GS" },
			{ year: 2010, stage: "GS" },
		],
	},
	{
		key: "bosnia",
		name: "Bosnia and Herzegovina",
		abbr: "BIH",
		conf: "UEFA",
		titles: 0,
		points: 3,
		gp: 3,
		w: 1,
		d: 0,
		l: 2,
		gs: 4,
		ga: 4,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/NFSBiH_logo.svg/200px-NFSBiH_logo.svg.png",
		tournaments: [{ year: 2014, stage: "GS" }],
	},
	{
		key: "iceland",
		name: "Iceland",
		abbr: "ISL",
		conf: "UEFA",
		titles: 0,
		points: 4,
		gp: 3,
		w: 1,
		d: 0,
		l: 2,
		gs: 2,
		ga: 5,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/KSI_logo.svg/200px-KSI_logo.svg.png",
		tournaments: [{ year: 2018, stage: "GS" }],
	},
	{
		key: "north-ireland",
		name: "Northern Ireland",
		abbr: "NIR",
		conf: "UEFA",
		titles: 0,
		points: 5,
		gp: 13,
		w: 3,
		d: 5,
		l: 5,
		gs: 13,
		ga: 23,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/IFA_logo.svg/200px-IFA_logo.svg.png",
		tournaments: [
			{ year: 1958, stage: "QF" },
			{ year: 1982, stage: "2GS" },
			{ year: 1986, stage: "GS" },
		],
	},
	{
		key: "bulgaria",
		name: "Bulgaria",
		abbr: "BUL",
		conf: "UEFA",
		titles: 0,
		points: 12,
		gp: 26,
		w: 3,
		d: 8,
		l: 15,
		gs: 22,
		ga: 53,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/BFU_logo.svg/200px-BFU_logo.svg.png",
		tournaments: [
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "GS" },
			{ year: 1970, stage: "GS" },
			{ year: 1974, stage: "GS" },
			{ year: 1986, stage: "R16" },
			{ year: 1994, stage: "SF" },
			{ year: 1998, stage: "GS" },
		],
	},

	// ── CONCACAF ─────────────────────────────────────────────────────────────
	{
		key: "east-germany",
		name: "East Germany",
		abbr: "DDR",
		conf: "UEFA",
		titles: 0,
		points: 2,
		gp: 6,
		w: 2,
		d: 1,
		l: 3,
		gs: 5,
		ga: 5,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Coat_of_arms_of_East_Germany.svg/200px-Coat_of_arms_of_East_Germany.svg.png",
		tournaments: [{ year: 1974, stage: "GS" }],
	},
	{
		key: "israel",
		name: "Israel",
		abbr: "ISR",
		conf: "UEFA",
		titles: 0,
		points: 2,
		gp: 3,
		w: 1,
		d: 1,
		l: 1,
		gs: 3,
		ga: 3,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Israel_Football_Association_%28logo%29.svg/200px-Israel_Football_Association_%28logo%29.svg.png",
		tournaments: [{ year: 1970, stage: "GS" }],
	},

	// ── CONCACAF ─────────────────────────────────────────────────────────────
	{
		key: "mexico",
		name: "Mexico",
		abbr: "MEX",
		conf: "CONCACAF",
		titles: 0,
		points: 49,
		gp: 57,
		w: 16,
		d: 13,
		l: 28,
		gs: 60,
		ga: 99,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/FMF_logo.svg/200px-FMF_logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "GS" },
			{ year: 1934, stage: "R16" },
			{ year: 1938, stage: "WD" },
			{ year: 1950, stage: "GS" },
			{ year: 1954, stage: "GS" },
			{ year: 1958, stage: "GS" },
			{ year: 1962, stage: "GS" },
			{ year: 1966, stage: "GS" },
			{ year: 1970, stage: "QF" },
			{ year: 1974, stage: "GS" },
			{ year: 1978, stage: "GS" },
			{ year: 1982, stage: "DNQ" },
			{ year: 1986, stage: "QF" },
			{ year: 1990, stage: "BAN" },
			{ year: 1994, stage: "R16" },
			{ year: 1998, stage: "R16" },
			{ year: 2002, stage: "R16" },
			{ year: 2006, stage: "R16" },
			{ year: 2010, stage: "R16" },
			{ year: 2014, stage: "R16" },
			{ year: 2018, stage: "R16" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "usa",
		name: "United States",
		abbr: "USA",
		conf: "CONCACAF",
		titles: 0,
		points: 28,
		gp: 34,
		w: 8,
		d: 6,
		l: 20,
		gs: 35,
		ga: 68,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/United_States_Soccer_Federation_logo.svg/200px-United_States_Soccer_Federation_logo.svg.png",
		tournaments: [
			{ year: 1930, stage: "SF" },
			{ year: 1934, stage: "R16" },
			{ year: 1950, stage: "GS" },
			{ year: 1990, stage: "GS" },
			{ year: 1994, stage: "R16" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "QF" },
			{ year: 2006, stage: "GS" },
			{ year: 2010, stage: "R16" },
			{ year: 2014, stage: "R16" },
			{ year: 2018, stage: "DNQ" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "costa-rica",
		name: "Costa Rica",
		abbr: "CRC",
		conf: "CONCACAF",
		titles: 0,
		points: 18,
		gp: 19,
		w: 5,
		d: 5,
		l: 9,
		gs: 20,
		ga: 32,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Escudo_de_la_Federaci%C3%B3n_Costarricense_de_F%C3%BAtbol.svg/200px-Escudo_de_la_Federaci%C3%B3n_Costarricense_de_F%C3%BAtbol.svg.png",
		tournaments: [
			{ year: 1990, stage: "R16" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "GS" },
			{ year: 2014, stage: "QF" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "honduras",
		name: "Honduras",
		abbr: "HON",
		conf: "CONCACAF",
		titles: 0,
		points: 3,
		gp: 9,
		w: 0,
		d: 3,
		l: 6,
		gs: 6,
		ga: 19,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Logo_of_Federaci%C3%B3n_Nacional_Aut%C3%B3noma_de_F%C3%BAtbol_de_Honduras.svg/200px-Logo_of_Federaci%C3%B3n_Nacional_Aut%C3%B3noma_de_F%C3%BAtbol_de_Honduras.svg.png",
		tournaments: [
			{ year: 1982, stage: "GS" },
			{ year: 2010, stage: "GS" },
			{ year: 2014, stage: "GS" },
		],
	},
	{
		key: "trinidad",
		name: "Trinidad and Tobago",
		abbr: "TRI",
		conf: "CONCACAF",
		titles: 0,
		points: 1,
		gp: 3,
		w: 0,
		d: 1,
		l: 2,
		gs: 0,
		ga: 4,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/TTFA_logo.png/200px-TTFA_logo.png",
		tournaments: [{ year: 2006, stage: "GS" }],
	},
	{
		key: "jamaica",
		name: "Jamaica",
		abbr: "JAM",
		conf: "CONCACAF",
		titles: 0,
		points: 3,
		gp: 3,
		w: 0,
		d: 1,
		l: 2,
		gs: 3,
		ga: 9,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Jamaica_national_football_team_badge.svg/200px-Jamaica_national_football_team_badge.svg.png",
		tournaments: [{ year: 1998, stage: "GS" }],
	},
	{
		key: "el-salvador",
		name: "El Salvador",
		abbr: "SLV",
		conf: "CONCACAF",
		titles: 0,
		points: 0,
		gp: 6,
		w: 0,
		d: 0,
		l: 6,
		gs: 1,
		ga: 22,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/FESFUT_logo.svg/200px-FESFUT_logo.svg.png",
		tournaments: [
			{ year: 1970, stage: "GS" },
			{ year: 1982, stage: "GS" },
		],
	},
	{
		key: "haiti",
		name: "Haiti",
		abbr: "HAI",
		conf: "CONCACAF",
		titles: 0,
		points: 1,
		gp: 3,
		w: 0,
		d: 1,
		l: 2,
		gs: 2,
		ga: 14,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Haiti_football_logo.svg/200px-Haiti_football_logo.svg.png",
		tournaments: [{ year: 1974, stage: "GS" }],
	},
	{
		key: "cuba",
		name: "Cuba",
		abbr: "CUB",
		conf: "CONCACAF",
		titles: 0,
		points: 3,
		gp: 3,
		w: 1,
		d: 1,
		l: 1,
		gs: 5,
		ga: 12,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Cuba_football.png/200px-Cuba_football.png",
		tournaments: [{ year: 1938, stage: "QF" }],
	},
	{
		key: "canada",
		name: "Canada",
		abbr: "CAN",
		conf: "CONCACAF",
		titles: 0,
		points: 3,
		gp: 6,
		w: 0,
		d: 1,
		l: 5,
		gs: 3,
		ga: 15,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Canada_Soccer_Logo.svg/200px-Canada_Soccer_Logo.svg.png",
		tournaments: [
			{ year: 1986, stage: "GS" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "panama",
		name: "Panama",
		abbr: "PAN",
		conf: "CONCACAF",
		titles: 0,
		points: 1,
		gp: 3,
		w: 0,
		d: 1,
		l: 2,
		gs: 2,
		ga: 11,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FEPAFUT_logo.svg/200px-FEPAFUT_logo.svg.png",
		tournaments: [{ year: 2018, stage: "GS" }],
	},

	// ── CAF ───────────────────────────────────────────────────────────────────
	{
		key: "morocco",
		name: "Morocco",
		abbr: "MAR",
		conf: "CAF",
		titles: 0,
		points: 32,
		gp: 24,
		w: 8,
		d: 6,
		l: 10,
		gs: 27,
		ga: 30,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Logo_FRMF.png/200px-Logo_FRMF.png",
		tournaments: [
			{ year: 1970, stage: "GS" },
			{ year: 1986, stage: "R16" },
			{ year: 1994, stage: "GS" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "GS" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "SF" },
		],
	},
	{
		key: "nigeria",
		name: "Nigeria",
		abbr: "NGR",
		conf: "CAF",
		titles: 0,
		points: 26,
		gp: 24,
		w: 8,
		d: 4,
		l: 12,
		gs: 24,
		ga: 38,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/NFF_logo.svg/200px-NFF_logo.svg.png",
		tournaments: [
			{ year: 1994, stage: "R16" },
			{ year: 1998, stage: "R16" },
			{ year: 2002, stage: "R16" },
			{ year: 2010, stage: "R16" },
			{ year: 2014, stage: "R16" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "cameroon",
		name: "Cameroon",
		abbr: "CMR",
		conf: "CAF",
		titles: 0,
		points: 21,
		gp: 25,
		w: 4,
		d: 6,
		l: 15,
		gs: 27,
		ga: 56,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/FECAFOOT_logo.png/200px-FECAFOOT_logo.png",
		tournaments: [
			{ year: 1982, stage: "GS" },
			{ year: 1990, stage: "QF" },
			{ year: 1994, stage: "GS" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "GS" },
			{ year: 2010, stage: "GS" },
			{ year: 2014, stage: "GS" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "ghana",
		name: "Ghana",
		abbr: "GHA",
		conf: "CAF",
		titles: 0,
		points: 19,
		gp: 13,
		w: 4,
		d: 3,
		l: 6,
		gs: 13,
		ga: 18,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/GFA_logo.svg/200px-GFA_logo.svg.png",
		tournaments: [
			{ year: 2006, stage: "R16" },
			{ year: 2010, stage: "QF" },
			{ year: 2014, stage: "GS" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "senegal",
		name: "Senegal",
		abbr: "SEN",
		conf: "CAF",
		titles: 0,
		points: 14,
		gp: 11,
		w: 4,
		d: 3,
		l: 4,
		gs: 12,
		ga: 15,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/FSF_logo.svg/200px-FSF_logo.svg.png",
		tournaments: [
			{ year: 2002, stage: "QF" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "ivory-coast",
		name: "Ivory Coast",
		abbr: "CIV",
		conf: "CAF",
		titles: 0,
		points: 9,
		gp: 9,
		w: 2,
		d: 1,
		l: 6,
		gs: 7,
		ga: 15,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/FIF_logo.svg/200px-FIF_logo.svg.png",
		tournaments: [
			{ year: 2006, stage: "GS" },
			{ year: 2010, stage: "GS" },
			{ year: 2014, stage: "GS" },
		],
	},
	{
		key: "south-africa",
		name: "South Africa",
		abbr: "RSA",
		conf: "CAF",
		titles: 0,
		points: 7,
		gp: 9,
		w: 2,
		d: 1,
		l: 6,
		gs: 8,
		ga: 16,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/SAFA_logo.svg/200px-SAFA_logo.svg.png",
		tournaments: [
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "GS" },
			{ year: 2010, stage: "GS" },
		],
	},
	{
		key: "algeria",
		name: "Algeria",
		abbr: "ALG",
		conf: "CAF",
		titles: 0,
		points: 12,
		gp: 12,
		w: 4,
		d: 1,
		l: 7,
		gs: 14,
		ga: 19,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/FAF_logo.svg/200px-FAF_logo.svg.png",
		tournaments: [
			{ year: 1982, stage: "GS" },
			{ year: 1986, stage: "GS" },
			{ year: 2010, stage: "GS" },
			{ year: 2014, stage: "R16" },
		],
	},
	{
		key: "tunisia",
		name: "Tunisia",
		abbr: "TUN",
		conf: "CAF",
		titles: 0,
		points: 6,
		gp: 18,
		w: 2,
		d: 4,
		l: 12,
		gs: 11,
		ga: 36,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/FTF_logo.svg/200px-FTF_logo.svg.png",
		tournaments: [
			{ year: 1978, stage: "GS" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "GS" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "egypt",
		name: "Egypt",
		abbr: "EGY",
		conf: "CAF",
		titles: 0,
		points: 6,
		gp: 9,
		w: 2,
		d: 2,
		l: 5,
		gs: 10,
		ga: 19,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/EFA_Logo.svg/200px-EFA_Logo.svg.png",
		tournaments: [
			{ year: 1934, stage: "R16" },
			{ year: 1990, stage: "GS" },
		],
	},
	{
		key: "angola",
		name: "Angola",
		abbr: "ANG",
		conf: "CAF",
		titles: 0,
		points: 2,
		gp: 3,
		w: 0,
		d: 2,
		l: 1,
		gs: 1,
		ga: 2,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/FAF_logo.svg/200px-FAF_logo.svg.png",
		tournaments: [{ year: 2006, stage: "GS" }],
	},
	{
		key: "togo",
		name: "Togo",
		abbr: "TOG",
		conf: "CAF",
		titles: 0,
		points: 1,
		gp: 3,
		w: 0,
		d: 1,
		l: 2,
		gs: 1,
		ga: 6,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FTF_logo.svg/200px-FTF_logo.svg.png",
		tournaments: [{ year: 2006, stage: "GS" }],
	},
	{
		key: "zaire",
		name: "DR Congo / Zaire",
		abbr: "ZAI",
		conf: "CAF",
		titles: 0,
		points: 0,
		gp: 3,
		w: 0,
		d: 0,
		l: 3,
		gs: 0,
		ga: 14,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Logo_F%C3%A9d%C3%A9ration_Football_Congo.svg/200px-Logo_F%C3%A9d%C3%A9ration_Football_Congo.svg.png",
		tournaments: [{ year: 1974, stage: "GS" }],
	},

	// ── AFC ───────────────────────────────────────────────────────────────────
	{
		key: "japan",
		name: "Japan",
		abbr: "JPN",
		conf: "AFC",
		titles: 0,
		points: 34,
		gp: 24,
		w: 8,
		d: 4,
		l: 12,
		gs: 28,
		ga: 35,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/Japan_Football_Association_logo.svg/200px-Japan_Football_Association_logo.svg.png",
		tournaments: [
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "R16" },
			{ year: 2006, stage: "GS" },
			{ year: 2010, stage: "R16" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "R16" },
			{ year: 2022, stage: "QF" },
		],
	},
	{
		key: "south-korea",
		name: "South Korea",
		abbr: "KOR",
		conf: "AFC",
		titles: 0,
		points: 34,
		gp: 37,
		w: 7,
		d: 7,
		l: 23,
		gs: 37,
		ga: 80,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/KFA_logo.svg/200px-KFA_logo.svg.png",
		tournaments: [
			{ year: 1954, stage: "GS" },
			{ year: 1986, stage: "GS" },
			{ year: 1990, stage: "GS" },
			{ year: 1994, stage: "GS" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "SF" },
			{ year: 2006, stage: "GS" },
			{ year: 2010, stage: "R16" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "iran",
		name: "Iran",
		abbr: "IRN",
		conf: "AFC",
		titles: 0,
		points: 10,
		gp: 18,
		w: 3,
		d: 2,
		l: 13,
		gs: 13,
		ga: 38,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Football_Federation_IR_Iran_logo.svg/200px-Football_Federation_IR_Iran_logo.svg.png",
		tournaments: [
			{ year: 1978, stage: "GS" },
			{ year: 1998, stage: "GS" },
			{ year: 2006, stage: "GS" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "GS" },
		],
	},
	{
		key: "saudi-arabia",
		name: "Saudi Arabia",
		abbr: "KSA",
		conf: "AFC",
		titles: 0,
		points: 12,
		gp: 18,
		w: 3,
		d: 4,
		l: 11,
		gs: 16,
		ga: 38,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/Saudi_Arabia_Football_Federation_Logo.svg/200px-Saudi_Arabia_Football_Federation_Logo.svg.png",
		tournaments: [
			{ year: 1994, stage: "R16" },
			{ year: 1998, stage: "GS" },
			{ year: 2002, stage: "GS" },
			{ year: 2006, stage: "GS" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "australia",
		name: "Australia",
		abbr: "AUS",
		conf: "AFC",
		titles: 0,
		points: 13,
		gp: 13,
		w: 3,
		d: 2,
		l: 8,
		gs: 14,
		ga: 30,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/b/bd/Football_Federation_Australia_logo.svg/200px-Football_Federation_Australia_logo.svg.png",
		tournaments: [
			{ year: 1974, stage: "GS" },
			{ year: 2006, stage: "R16" },
			{ year: 2010, stage: "GS" },
			{ year: 2014, stage: "GS" },
			{ year: 2018, stage: "GS" },
			{ year: 2022, stage: "R16" },
		],
	},
	{
		key: "north-korea",
		name: "North Korea",
		abbr: "PRK",
		conf: "AFC",
		titles: 0,
		points: 5,
		gp: 7,
		w: 1,
		d: 2,
		l: 4,
		gs: 6,
		ga: 21,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/DPRK_FA_logo.svg/200px-DPRK_FA_logo.svg.png",
		tournaments: [
			{ year: 1966, stage: "QF" },
			{ year: 2010, stage: "GS" },
		],
	},
	{
		key: "iraq",
		name: "Iraq",
		abbr: "IRQ",
		conf: "AFC",
		titles: 0,
		points: 1,
		gp: 3,
		w: 0,
		d: 1,
		l: 2,
		gs: 1,
		ga: 4,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Iraqi_Football_Association_logo.svg/200px-Iraqi_Football_Association_logo.svg.png",
		tournaments: [{ year: 1986, stage: "GS" }],
	},
	{
		key: "china",
		name: "China",
		abbr: "CHN",
		conf: "AFC",
		titles: 0,
		points: 0,
		gp: 3,
		w: 0,
		d: 0,
		l: 3,
		gs: 0,
		ga: 9,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/Chinese_Football_Association_logo.svg/200px-Chinese_Football_Association_logo.svg.png",
		tournaments: [{ year: 2002, stage: "GS" }],
	},
	{
		key: "uae",
		name: "United Arab Emirates",
		abbr: "UAE",
		conf: "AFC",
		titles: 0,
		points: 1,
		gp: 3,
		w: 0,
		d: 1,
		l: 2,
		gs: 2,
		ga: 11,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/UAE_FA_Logo.svg/200px-UAE_FA_Logo.svg.png",
		tournaments: [{ year: 1990, stage: "GS" }],
	},
	{
		key: "kuwait",
		name: "Kuwait",
		abbr: "KWT",
		conf: "AFC",
		titles: 0,
		points: 1,
		gp: 3,
		w: 0,
		d: 1,
		l: 2,
		gs: 2,
		ga: 6,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Kuwait_FA_logo.svg/200px-Kuwait_FA_logo.svg.png",
		tournaments: [{ year: 1982, stage: "GS" }],
	},
	{
		key: "qatar",
		name: "Qatar",
		abbr: "QAT",
		conf: "AFC",
		titles: 0,
		points: 0,
		gp: 3,
		w: 0,
		d: 0,
		l: 3,
		gs: 1,
		ga: 7,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Qatar_national_football_team_logo.svg/200px-Qatar_national_football_team_logo.svg.png",
		tournaments: [{ year: 2022, stage: "GS" }],
	},
	{
		key: "dutch-east-indies",
		name: "Dutch East Indies",
		abbr: "DEI",
		conf: "AFC",
		titles: 0,
		points: 0,
		gp: 1,
		w: 0,
		d: 0,
		l: 1,
		gs: 0,
		ga: 6,
		badge:
			"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dutch_East_Indies.svg/200px-Flag_of_the_Dutch_East_Indies.svg.png",
		tournaments: [{ year: 1938, stage: "R16" }],
	},

	// ── OFC ───────────────────────────────────────────────────────────────────
	{
		key: "new-zealand",
		name: "New Zealand",
		abbr: "NZL",
		conf: "OFC",
		titles: 0,
		points: 3,
		gp: 9,
		w: 0,
		d: 3,
		l: 6,
		gs: 5,
		ga: 22,
		badge:
			"https://upload.wikimedia.org/wikipedia/en/thumb/6/65/New_Zealand_Football_logo.svg/200px-New_Zealand_Football_logo.svg.png",
		tournaments: [
			{ year: 1982, stage: "GS" },
			{ year: 2010, stage: "GS" },
		],
	},
];

// ---------------------------------------------------------------------------
// Write individual team JSON files
// ---------------------------------------------------------------------------
const ALL_WC_YEARS = [
	1930, 1934, 1938, 1950, 1954, 1958, 1962, 1966, 1970, 1974, 1978, 1982, 1986,
	1990, 1994, 1998, 2002, 2006, 2010, 2014, 2018, 2022,
];

for (const team of TEAMS) {
	const { key, tournaments } = team;
	const existingYears = new Set(tournaments.map((t) => t.year));
	const filled = ALL_WC_YEARS.map((year) =>
		existingYears.has(year)
			? tournaments.find((t) => t.year === year)
			: { year, stage: "DNQ" },
	);
	fs.writeFileSync(
		path.join(DATA_DIR, `${key}.json`),
		JSON.stringify(filled, null, 2),
	);
}

// ---------------------------------------------------------------------------
// Write teams-index.json (metadata only — no tournaments array)
// ---------------------------------------------------------------------------
const index = TEAMS.map(
	(
		{ key, name, abbr, conf, titles, points, gp, w, d, l, gs, ga, badge },
		i,
	) => ({
		key,
		name,
		abbr,
		conf,
		rank: i + 1,
		titles,
		points,
		gp,
		w,
		d,
		l,
		gs,
		ga,
		gd: gs - ga,
		winPct: gp ? Math.round((w / gp) * 100) : 0,
		appearances: TEAMS.find((t) => t.key === key).tournaments.filter(
			(t) => !["DNQ", "DNE", "WD", "BAN"].includes(t.stage),
		).length,
		badge,
	}),
);

fs.writeFileSync(
	path.join(__dirname, "teams-index.json"),
	JSON.stringify(index, null, 2),
);

console.log(`✓ Written ${TEAMS.length} team files to data/`);
console.log(`✓ Written teams-index.json (${index.length} teams)`);
