#!/usr/bin/env node
/**
 * build_w_legislators.js
 *
 * Fetches all CURRENT U.S. state legislators from Open States API v3,
 * filters to people whose names start with "W", and writes:
 *   - w_state_legislators.json
 *   - w_state_legislators.js (ESM default export)
 *
 * Usage:
 *   OPENSTATES_API_KEY=YOUR_KEY node build_w_legislators.js
 *
 * Docs:
 * - API v3 overview: https://docs.openstates.org/api-v3/
 * - Interactive docs: https://v3.openstates.org/docs
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import https from "https";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const API_KEY = process.env.OPENSTATES_API_KEY;
if (!API_KEY) {
  console.error("ERROR: Missing OPENSTATES_API_KEY env var.");
  console.error(
    "Get a free key at https://docs.openstates.org/api-v3/ and try again."
  );
  process.exit(1);
}

const BASE = "https://v3.openstates.org";

/** Minimal HTTPS GET wrapper returning JSON */
function getJSON(url) {
  const headers = { "X-API-KEY": API_KEY, Accept: "application/json" };
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers }, (res) => {
        let data = "";
        res.on("data", (chunk) => (data += chunk));
        res.on("end", () => {
          if (res.statusCode && res.statusCode >= 200 && res.statusCode < 300) {
            try {
              resolve(JSON.parse(data));
            } catch (e) {
              reject(e);
            }
          } else {
            reject(new Error(`HTTP ${res.statusCode}: ${data}`));
          }
        });
      })
      .on("error", reject);
  });
}

/** Fetch list of state jurisdictions (excludes territories/DC by default) */
async function fetchStateJurisdictions() {
  const out = [];
  let page = 1;
  while (true) {
    await sleep(10000); // Wait 10 seconds before each API call to avoid rate limit
    const url = `${BASE}/jurisdictions?classification=state&per_page=50&page=${page}`;
    const json = await getJSON(url);
    if (!json || !json.results || json.results.length === 0) break;
    out.push(...json.results);
    if (!json.pagination || page >= json.pagination.max_page) break;
    page++;
  }
  return out;
}

/**
 * Fetch current people (legislators) for a jurisdiction, paginated.
 * We set current_role=true to only include current officeholders.
 */
async function fetchPeopleForJurisdiction(jurisdictionId) {
  const people = [];
  let page = 1;
  while (true) {
    await sleep(10000); // Wait 10 seconds before each API call to avoid rate limit
    const url = `${BASE}/people?jurisdiction=${encodeURIComponent(
      jurisdictionId
    )}&current_role=true&per_page=50&page=${page}`;
    const json = await getJSON(url);
    if (!json || !json.results || json.results.length === 0) break;
    people.push(...json.results);
    if (!json.pagination || page >= json.pagination.max_page) break;
    page++;
  }
  return people;
}

function nameOrLastNameStartsWith(person) {
  if (!person || !person.name) return false;
  const n = person.name.trim().toUpperCase();
  const initials = ["W", "L", "J", "B"];
  // Split name into words (first, last, etc.)
  const parts = n.split(/\s+/);
  return parts.some((part) => initials.includes(part[0]));
}

function simplify(person) {
  // Keep key fields only
  return {
    id: person.id,
    name: person.name,
    given_name: person.given_name || null,
    family_name: person.family_name || null,
    party: person.party || person.current_party || null,
    current_role: person.current_role || null,
    jurisdiction:
      (person.jurisdiction &&
        (person.jurisdiction.name || person.jurisdiction.id)) ||
      null,
    openstates_url: person.openstates_url || null,
  };
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  console.log("Fetching state jurisdictions...");
  const jurisdictions = await fetchStateJurisdictions();
  console.log(`Found ${jurisdictions.length} jurisdictions.`);

  let results = [];
  for (const j of jurisdictions) {
    console.log(`Fetching people for ${j.name} (${j.id})...`);
    const people = await fetchPeopleForJurisdiction(j.id);
    const filtered = people.filter(nameOrLastNameStartsWith).map(simplify);
    results.push(...filtered);
    await sleep(7000); // Wait 7 seconds between requests to avoid rate limit
  }

  // Sort by name
  results.sort((a, b) => a.name.localeCompare(b.name, "en"));

  const jsonPath = path.join(__dirname, "w_state_legislators.json");
  const jsPath = path.join(__dirname, "w_state_legislators.js");

  fs.writeFileSync(jsonPath, JSON.stringify(results, null, 2));
  fs.writeFileSync(
    jsPath,
    `// Auto-generated by build_w_legislators.js\nexport default ${JSON.stringify(
      results,
      null,
      2
    )};\n`
  );

  console.log(`Wrote ${results.length} legislators to:`);
  console.log(`- ${jsonPath}`);
  console.log(`- ${jsPath}`);
}

main().catch((err) => {
  console.error("Failed:", err);
  process.exit(1);
});
